# Generated by Django 5.1.4 on 2024-12-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviewproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='product',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product'),
        ),
    ]
